# Generated by Django 5.2.4 on 2025-08-01 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: PVC Soldável, Aço Carbono', max_length=100, unique=True)),
                ('rugosidade_mm', models.FloatField(help_text='Rugosidade absoluta (ε) em milímetros')),
            ],
        ),
        migrations.CreateModel(
            name='Tubulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro_nominal', models.CharField(help_text="Representação comercial. Ex: '50mm' ou '2 polegadas'", max_length=20)),
                ('diametro_interno_mm', models.FloatField(help_text='Diâmetro interno real em milímetros (usado nos cálculos)')),
                ('diametro_externo_mm', models.FloatField(help_text='Diâmetro externo real em milímetros')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubulacoes', to='calculator.material')),
            ],
            options={
                'ordering': ['material', 'diametro_interno_mm'],
                'unique_together': {('material', 'diametro_interno_mm')},
            },
        ),
    ]
