# Generated by Django 5.2.4 on 2025-08-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprimentoEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento_m', models.FloatField(help_text='Comprimento equivalente (Leq) em metros')),
                ('tubulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.tubulacao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.peca')),
            ],
            options={
                'unique_together': {('peca', 'tubulacao')},
            },
        ),
    ]
