# Generated by Django 5.2.4 on 2025-08-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_peca_comprimentoequivalente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_projeto', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('consumo_diario_litros', models.FloatField()),
                ('horas_funcionamento', models.FloatField()),
                ('rendimento_bomba', models.FloatField()),
                ('tipo_succao', models.CharField(max_length=10)),
                ('altura_geo_suc_m', models.FloatField()),
                ('comp_real_suc_m', models.FloatField()),
                ('altura_geo_rec_m', models.FloatField()),
                ('comp_real_rec_m', models.FloatField()),
                ('pecas_suc', models.JSONField(default=dict)),
                ('pecas_rec', models.JSONField(default=dict)),
                ('q_m3_h', models.FloatField()),
                ('dr_nominal', models.CharField(max_length=50)),
                ('ds_nominal', models.CharField(max_length=50)),
                ('h_man_total_m', models.FloatField()),
                ('potencia_comercial_cv', models.FloatField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
