# Generated by Django 5.2.4 on 2025-08-06 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(help_text='Ex: KSB, Grundfos, Dancor', max_length=100)),
                ('modelo', models.CharField(help_text='Ex: Submersa KRT BIO 50-160/152', max_length=100)),
                ('user', models.ForeignKey(help_text='Usuário proprietário desta bomba', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fabricante', 'modelo'],
                'unique_together': {('user', 'fabricante', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='PontoCurvaBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazao_m3h', models.FloatField(help_text='Ponto de vazão (Q) em m³/h')),
                ('altura_m', models.FloatField(help_text='Ponto de altura manométrica (H) em m.c.a.')),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_da_curva', to='calculator.bomba')),
            ],
            options={
                'ordering': ['vazao_m3h'],
            },
        ),
    ]
