# Generated by Django 5.2.4 on 2025-08-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_bomba_pontocurvabomba'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pontocurvabomba',
            unique_together={('bomba', 'vazao_m3h')},
        ),
    ]
